services:

  app-8.2:
    build:
      dockerfile: ./resources/docker/Dockerfile
      args:
        PHP_VERSION: 8.2
    hostname: rest-api-app-82
    container_name: "${PROJECT_NAME}-api-8.2"
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - app-db
      - app-cache
    networks:
      - app-network
    environment:
      - PHP_IDE_CONFIG=serverName=rest-api-app-82
      - APP_ENV=development
      - APP_ENV_ADAPTER=dotenv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/fpm-ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  app-8.3:
    build:
      dockerfile: ./resources/docker/Dockerfile
      args:
        PHP_VERSION: 8.3
    hostname: rest-api-app-83
    container_name: "${PROJECT_NAME}-api-8.3"
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - app-db
      - app-cache
    networks:
      - app-network
    environment:
      - PHP_IDE_CONFIG=serverName=rest-api-app-83
      - APP_ENV=development
      - APP_ENV_ADAPTER=dotenv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/fpm-ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  app-8.4:
    build:
      dockerfile: ./resources/docker/Dockerfile
      args:
        PHP_VERSION: 8.4
    hostname: rest-api-app-84
    container_name: "${PROJECT_NAME}-api-8.4"
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - app-db
      - app-cache
    networks:
      - app-network
    environment:
      - PHP_IDE_CONFIG=serverName=rest-api-app-84
      - APP_ENV=development
      - APP_ENV_ADAPTER=dotenv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/fpm-ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  app-8.5:
    build:
      dockerfile: ./resources/docker/Dockerfile
      args:
        PHP_VERSION: 8.5
    hostname: rest-api-app-85
    container_name: "${PROJECT_NAME}-api-8.5"
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - app-db
      - app-cache
    networks:
      - app-network
    environment:
      - PHP_IDE_CONFIG=serverName=rest-api-app-85
      - APP_ENV=development
      - APP_ENV_ADAPTER=dotenv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/fpm-ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  app-db:
    container_name: "${PROJECT_NAME}-db"
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=phalcon
      - MYSQL_DATABASE=phalcon
      - MYSQL_PASSWORD=secret
    networks:
      - app-network

  app-cache:
    container_name: "${PROJECT_NAME}-cache"
    image: redis:8-alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
